name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add branch to env
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@a5609cb39f57be157c39b77359abfaa43aeaeb8f
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Dotenv Action^
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          log-variables: NEXTCLOUD_VERSION

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@b67fef219a3c5542bf1d0948862a08152653b4d4
        with:
          images: |
            maximilianpohle/docker-alpine-nginx-modsec
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern=${{ env.BRANCH }}
            type=sha

      - name: Build and push Docker images
        uses: docker/build-push-action@4e4ee680f69700760d5620a94c020aef883043aa
        with:
          push: true
          build-args: |
            NEXTCLOUD_VERSION=${{ steps.dotenv.outputs.nextcloud_version }}
          cache-from: type=registry,ref=maximilianpohle/docker-alpine-nginx-modsec:${{ env.BRANCH }}
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@69cbbc0cbbf6a2b0bab8dcf0e9f2d7ead08e87e4
        with:
          image-ref: maximilianpohle/docker-alpine-nginx-modsec:${{ env.BRANCH }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
